### ISSUE TITLE
Can't set yDomain on Line with focus chart on y2Axis

### ISSUE THREAD

**Issue by nikolayanchev** [nvd3-community/nvd3#102]
I am trying to implement a line with focus chart that takes a lot of values (date, value). The trouble is that the difference between the min and max value is about 1000 units and this breaks the focus chart (the small chart that is used to focus), the lines of the small chart go over the big chart. Now i am trying to find a functionality to set the yDomain for the small (focus chart), but can't seem to find it.am i looking in the wrong places or this functionality does't exist?

**Comment by liquidpele** [comment]
Open issues under novus/nvd3
