### ISSUE TITLE
Loading Animation

### ISSUE THREAD

**Issue by Maraket** [nvd3-community/nvd3#109]
More a feature request then an actual issue, I think having a loading animation for the graphs, similar to what is experienced in chartJs. I was strongly considering using nvd3 for a project I am working on, though as the client is pushing for the smooth load of pie/doughnut charts, I had to take it off the table since I haven't found any way to incorporate this in the needed timeframe (sadly not to good at d3).

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
