### ISSUE TITLE
Are there any plans on developing version 2.0?

### ISSUE THREAD

**Issue by varvarvar** [nvd3-community/nvd3#11]
Do you guys think Novus' branch of version 2.0 worth looking into or are there some permanent problems that you decided not to include it into your branches?

Thanks!

**Comment by liquidpele** [comment]
Well, basically the guy who was spear-heading that left Novus back in June of 2014 and the 2.x branch was never finished.   I spoke to the other person still there about my possibly forking and he recommended I start with the development branch, so I did that.  I honestly don't know if there was any of their 2.x code in there or not, but I did glance around in their 2.x branch and I didn't see any mind blowing differences, so my branch might be more refactored than that one was at this point :p  Also, I'm much more a fan of incremental changes than massive refactors (that usually never get completed) and breaking backward compatibility.

If you want you go grab their 2.x branch and poke around, and if you see anything worth doing in this fork then we might be able to make that happen.
