### ISSUE TITLE
Tooltip information is incorrect

### ISSUE THREAD

**Issue by david-nguyen** [nvd3-community/nvd3#110]
Hi your documentation is incorrect for tooltipContent under the various charts:

> Deprecated. Use chart.tooltip.contentGenerator or chart.interactiveGuideline.tooltip.contentGenerator to control tooltip content

Which does not work, you have to use `chart.interactiveLayer.tooltip.contentGenerator`. Documentation is not available for that either but a helpful user posted info on how to use the one data field:

    chart.tooltip.contentGenerator(function (d) {
          var html = "<h2>"+d.value+"</h2> <ul>";

          d.series.forEach(function(elem){
            html += "<li><h3 style='color:"+elem.color+"'>"
                    +elem.key+"</h3> : <b>"+elem.value+"</b></li>";
          })
          html += "</ul>"
          return html;
     })

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
