### ISSUE TITLE
Possible to exclude all categories except clicked on single click?

### ISSUE THREAD

**Issue by brylie** [nvd3-community/nvd3#112]
When clicking chart categories, the default behavior is to exclude that category from the chart. E.g. on the stacked bar chart, single clicking or touching a category hides it.

Is it possible to reverse this behavior, so that single clicking a category hides all other categories?

**Comment by brylie** [comment]
I noticed that double clicking has the desired effect on a desktop/laptop with mouse. However, we are also rendering these charts on tablets/phones that may not support double clicking. Is there a way for tablet users to quickly show only a single category?

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
