### ISSUE TITLE
Using barColor on multiBarHorizontalChart example very confusing and seems incorrect

### ISSUE THREAD

**Issue by PeterVermont** [nvd3-community/nvd3#115]
Although the legend indicates a consistent color for each series bar, the chart does not actually show this:
![image](https://cloud.githubusercontent.com/assets/889233/17064916/0e83f6d2-500d-11e6-98ae-e78578764d63.png)

BarColor is used in the example and is called with i up to the number of all total bars (series * items_per_series).

Color gets called with i set between 0 and (numSeries - 1) and threfore seems a better choice. This is the example with BarColor changed to color:

![image](https://cloud.githubusercontent.com/assets/889233/17065143/37721b90-500e-11e6-82d3-67be3ae14c3e.png)

**Comment by liquidpele** [comment]
please open issues under the novus/nvd3 repo, thanks.
