### ISSUE TITLE
Detach view finder from main graph - Line Chart With View Finder

### ISSUE THREAD

**Issue by PrashansaM-optimus** [nvd3-community/nvd3#116]
Hello,

Is there a way to detach the view finder from the main graph area of 'Line Chart with View Finder'. 
Url - http://nvd3.org/examples/lineWithFocus.html 

Currently the graph contains the 3 main graph elements having the following classes:
- nv-legendWrap 
- .nv-focus
- .nv-context

I want to detach the .nv-context graph element from the main svg and put this in other svg so that there could be one panel that contains 2 panes (one for main graph and other for view finder).

Refer the below screenshot for further clarification of the problem.
![nvd3](https://cloud.githubusercontent.com/assets/2578616/17850299/35f47036-687a-11e6-8125-6584c4d71faf.png)

Please provide some solution to this.
**Note: Need to ensure that none of the functionality gets affected after detaching it.**
Thanks

**Comment by liquidpele** [comment]
open issues under the novus project please, thanks.
