### ISSUE TITLE
missing parameter declaration

### ISSUE THREAD

**Issue by ehartford** [nvd3-community/nvd3#118]
in the force directed graph model, parameters getX and getY are not declared, will this not create global variables?

https://github.com/nvd3-community/nvd3/blob/master/src/models/forceDirectedGraph.js#L163

I would expect to see something here

https://github.com/nvd3-community/nvd3/blob/master/src/models/forceDirectedGraph.js#L27

like 

    ,getX = d3.functor(0.0)
    ,getY = d3.functor(0.0)

**Comment by liquidpele** [comment]
Please create issues/PRs on the novus repo, thanks.
