### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jrharshath** [nvd3-community/nvd3#123]
I suppose this is not so much of an issue with nvd3, but more of a discussion.

I've recently started using nvd3, and reading a lot of its code (which seems to be the best form of documentation for nvd3). It occurred to me that more documentation for nvd3 would definitely help further its adoption. 

It also is clear that it is designed for reusability and extensibility, and it would be possible for nvd3 users to create new models of their own quickly. A tutorial or two for creating custom visualizations in nvd3's reusable style would also be a great resource for new nvd3 users.

I myself have only just begun using nvd3, and I'm finding the need to create a few custom visualizations. If some of those seem generic enough to be useful to others, I shall contribute them back to this project. And if time permits, I shall also write up some documentation that can be helpful to others.

On a slightly related subject: is there a reason why there are no basic map-based visualizations included in nvd3 already? I think those would be terrific to have as well. I'm building a few map-based visualizations (first, without nvd3, but I'll try to port them into the nvd3 style of doing things). I'd like to know the community's thoughts on building map-based visualizations using nvd3.

Regards,
Harshath

**Comment by liquidpele** [comment]
Please open issues/PRs under the novus/nvd3 repo, thanks.
