### ISSUE TITLE
Discussion about where to do active dev

### ISSUE THREAD

**Issue by liquidpele** [nvd3-community/nvd3#127]
@RenatoUtsch @portante @ThomasBrierley 

So I'm a little concerned about the fact that novus has once again apparently dropped off the face of the Earth in regards to nvd3.  I don't have access to add people or do anything under their org, only to manage the nvd3 repo... and I'd like to add more people since I don't always have time to vet code or reply to issues.   

If we try to move opening pull requests and issues over to this nvd3-community repo, would you guys be willing to help out maintaining the project?

**Comment by RenatoUtsch** [comment]
I'd really like to, but realistically I won't have time until the end of May.

After that I might consider helping, it'd be nice to help with nvd3.

**Comment by ThomasBrierley** [comment]
Yes, when I have time: I can at the least help sift, merge obvious things, get general git PR issues in shape etc. Although I'd like to be upfront about not knowing D3 as thoroughly as I should, so I will not be merging anything I feel too uncertain about (including my own code) without other's reviewing it first.

We all have other commitments and can't promise to always be available, so multiple members to keep things under control is a smart move... considering the continuous volume of activity on nvd3 I think you could do with a break @liquidpele :stuck_out_tongue:

**Comment by portante** [comment]
Of late, my focus has been to use Grafana and Kibana for the visualizations I need.  And I have seen good things from the c3 effort as well, which is in used by the PatternFly effort for UI design.

**Comment by samraj-milton** [comment]
Hi in nv.d3.js a variable atleastOnePoint = false; needs to be declared.In current source it is not declared but   it is use this is the reason we get the atleastOnePoint is undefined error while we move the mouse over the graph

**Comment by ThomasBrierley** [comment]
@samraj-milton https://github.com/novus/nvd3

**Comment by ebbmo** [comment]
Hi guys,

I would love to see the NVD3 library move into public maintenance... Like the others: If there is spare time left, i'm willing to commit as well.

@liquidpele What is keeping you from moving it?

KR, ebbmo
