### ISSUE TITLE
Overridden 'tooltipShow' dispatch reverts to default when window is resized.

### ISSUE THREAD

**Issue by naunga** [nvd3-community/nvd3#13]
I've created an example of this issue here: http://embed.plnkr.co/nHTxuLNC2sB5us10wF4X/preview

To see the issue do the following:
1. Open http://embed.plnkr.co/nHTxuLNC2sB5us10wF4X/preview
2. Mouse over any of the bars and note the style of the tooltip.
3. Resize the window.
4. Mouse over any of the bars again. You'll see that the tooltip is different.

There is also some console logging to illustrate this.

Commenting out the call to nv.utils.windowResize(chart.update) "fixes" this, but of course the chart does not resize as a result.

**Comment by liquidpele** [comment]
Oh weird, will look into that..

**Comment by liquidpele** [comment]
Well, your example pages won't load anymore :(

However, I did look at what you were doing, and I think you were just trying to modify the look of the tooltip right?  Why not use the tooltipContent option for that?  It's pretty much designed to handle the tooltip format.  Beyond that, you could override the elementMouseover.tooltip dispatch instead, which is outside the chart generation code so it doesn't get overwritten on chart.update().

**Comment by naunga** [comment]
liquidpele said:
> "...you could override the elementMouseover.tooltip dispatch instead..."

Damnit! This is a PEBCAK. 

I had tried that, but in looking over the code where I did I had it as elementMouseover.tooltip**Show**, which of course caused undesired behavior. 

This is why you shouldn't code with a cold. :-p

Mea culpa. Thanks for the quick reply.

**Comment by liquidpele** [comment]
Glad it's working now, cheers!
