### ISSUE TITLE
Setting groupSpacing on multiBarHorizontalChart doesn't seem to work

### ISSUE THREAD

**Issue by inolasco** [nvd3-community/nvd3#14]
I glanced at the model code, and I could be wrong, but it seems to me that multiBar has a hardcoded groupSpacing=0.1, and if my understanding is correct, multiBarHorizontalChart and others inherit this instead of using the value we set for groupSpacing.

Either that, or I'm doing something wrong :P Any ideas?

Thanks for the awesome work!

**Comment by liquidpele** [comment]
Actually multiBarChart inherits from multiBar, and multiBarHorizontalChart inherits from multiBarHorizontal, but yea multiBarHorizontal looks to have it hard coded... easy to add the option though :p

**Comment by liquidpele** [comment]
Should have the option now, in development branch.  Also added documentation item for it.

**Comment by inolasco** [comment]
Thanks, you rock!
