### ISSUE TITLE
Option of using a filter to select points to be drawn?

### ISSUE THREAD

**Issue by portante** [nvd3-community/nvd3#15]
When using lineChart(), I notice that the rendered svg includes the path for the lines, and all the points, though by default the points have an opacity of 0 so they don't show.

As we add more lines to a chart, this can really decrease the ability of a browser to render the graphs as we interact with the rest of the page.

I was thinking of adding the ability to specify a filter function which would give the caller the ability to dictate which of the set of points should be drawn.  This way, one could turn them all off, or draw only those that are interesting meeting some characteristic, or turn them all on.

I don't see that functionality now, so figured I'd post this in case I am missing something fundamental.

Thanks ahead of time.

**Comment by liquidpele** [comment]
That would be a great addition!  You're correct that it doesn't handle massive data points very well at present.   I had thought about writing a sanity checker in there that would take a sampling of the data if the number of points  was too high for the width of the graph container, but really any implementation you think is useful is welcome.

**Comment by portante** [comment]
I'll post a pull request once I figure out how to do it.  ;)

Any suggestions welcome.

**Comment by portante** [comment]
Okay, so how does this sound?

For `lineChart()` (my focus right now, not considering other uses of `scatter` right now...):

* "`notActive`" attribute of a data point will hide/show under both the interactive guideline display of that point, and the mouse over behavior (`useVoronoi` or not)
  * This means that when `notActive` is "`true`", no data points will be present in the SVG dom elements (potentially reducing the amount of data in the DOM substantially)
* to do this, we change `scatter.js` to not render points with `notActive` set to "`true`", and document that the caller will see this behavior with with the default `pointActive()` function
  * We would then also document that one could write a substitute `pointActive()` function to filter point displays
  * We would also not that `pointActive()` does not affect the lines drawn in a `lineChart`, but that this would eliminate points in a `scatterChart()` (and others)

What do you think?

**Comment by portante** [comment]
Here is this gist of the change: https://gist.github.com/portante/dcaba72e948405c92308

Gotta write some tests for it still...
