### ISSUE TITLE
Updating graph data with empty data [] does not clear graph

### ISSUE THREAD

**Issue by liquidpele** [nvd3-community/nvd3#2]
To reproduce:

Render any chart with some data.
some time later, update the data to be []
What happens:
The chart will display "No Data Available", but will keep the last data shown.

https://github.com/liquidpele/nvd3/issues/29

**Comment by krasnoukhov** [comment]
:+1: for fixing that. It appears that it worked on `1.1.15.beta` :sob:

**Comment by liquidpele** [comment]
It's hard to compare with the old novus code at this point, but that's interesting... it's possible I broke it I guess.  This fork is based on their development branch though, so I wonder if it works there or not...

**Comment by liquidpele** [comment]
should be fixed now

**Comment by krasnoukhov** [comment]
Thanks @liquidpele, this is really appreciated!

**Comment by liquidpele** [comment]
Thank @jamesgarfield  who made a pull request for it.  Only in the development branch right now mind you ;)

**Comment by krasnoukhov** [comment]
I can confirm it's fixed. Using development branch in production :dancer: Thanks @jamesgarfield
