### ISSUE TITLE
Scatter on multi chart

### ISSUE THREAD

**Issue by vid** [nvd3-community/nvd3#21]
Is it possible to include scatter series on the multi chart[1]? Thanks! 

[1] https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/multiChart.html

**Comment by liquidpele** [comment]
Not yet.  I'm moving toward trying to consolidate more of the charts though and that would be a valid thing to do.   If you wanted to code it up feel free to send a pull request!

**Comment by vid** [comment]
I'm not specialized in d3 and really wouldn't know where to start with nvd3, plus I guess if you're going to rewrite it may not be the best thing to do, but if there is some good starting point I could look into it. Right now I'm looking to fake it with 'line' and style sheets. thanks again.

**Comment by liquidpele** [comment]
Well, if you did want to look at it at all, basically in /src/models/multiChart.js is the whole thing for that chart.  It creates 2 instances of line.js and two instances of multiBar.js and two instances of stackedArea.js for the chart... so it's basically set to have a max of 6 things.  You'd just need to add a scatter.js or two in there as well and pretty much do the same things the other charts are doing.  Or, more realistically, it would be nice to have a list of each kind so you could add as many as you wanted :)

**Comment by vid** [comment]
I had looked at the file and was wondering… why two? and why no scatter in the first place. I guess it was designed for a particular demo rather than general functionality?

I can try to work on it Monday.

**Comment by liquidpele** [comment]
Yea, the original nvd3 code was build specifically for Novus doing particular things, they probably only needed two so that's all they added, lol.
