### ISSUE TITLE
[documentation] tooltipContent example is incorrect

### ISSUE THREAD

**Issue by ovvn** [nvd3-community/nvd3#28]
The example is used everywhere
```
chart.tooltipContent(function (key, y, e, graph) {
    var content = '<h3 style="background-color: ';
    content += e.color + '">';
    content += key + '</h3><p>' +  y + '</p>';
    return content;
})
```
is missing x parameter, e.g.
```
chart.tooltipContent(function (key, x, y, e, graph) {
    var content = '<h3 style="background-color: ';
    content += e.color + '">';
    content += key + '</h3><p>' +  y + '</p>';
    return content;
})
```

**Comment by liquidpele** [comment]
Actually, that example is a copy/paste from the pie chart and is correct for that chart.   That's why in the description I said that the params differ per chart and you'll want to console.log() all params to see what they are if you're not sure.  I'm actually looking at fixing the tooltip mess, since there are other issues with it as well, and hopefully I'll be able to make things consistent.

**Comment by ovvn** [comment]
I see, that's why  things like ```e.color``` won't work in other charts.
Also, I've tested the following code
```javascript
var colors = ['#5f9e5f', '#269abc', '#d58512', '#d43f3a'];

nv.addGraph(function() {
  var chart = nv.models.pieChart()
      .x(function(d) { return d.label })
      .y(function(d) { return d.value })
      .showLabels(true)
      .color(colors)
      .tooltipContent(function (key, y, e, graph) {
          var content = '<h3 style="background-color: ';
          content += e.color + '">';
          content += key + '</h3><p>' +  y + '</p>';
    	return content;
	 })

    d3.select("#chart svg")
        .datum(data)
      .transition().duration(1200)
        .call(chart);

  return chart;
});
```
And ```e.color``` is ```undefined``` within the tooltip.

**Comment by liquidpele** [comment]
If color is undefined for you, you're probably not using the updated version of nvd3.  I added that in my fork.   I know it works though, because the pieChart example uses that exact tooltip snippet.

**Comment by ovvn** [comment]
Yes, you're right. Updated version's pieChart has this e.color feature.

**Comment by liquidpele** [comment]
Glad you got it working then :)
