### ISSUE TITLE
updating lineWithFocusChart 

### ISSUE THREAD

**Issue by marcinag** [nvd3-community/nvd3#29]
I'm trying to present "real-time" time series as lineWithFocusChart plot. I mean that there's an XHR polling every 10 seconds that fetches data from the cloud server. The XHR request always returns full set of data (i.e., it grows over time). 

When number of data points exceeds 5000 thousand, website's performance gradually worsens, and finally tab crashes after some minutes. Heap snapshot also grows in the same time.

Here is the code that I use:

```
var chart=null;

var _plotGraph = function(jsonData, x, init) {
'use strict';
  
  if (jsonData === null ) {
    return;
  }

  
  var yAxisLabel = '';
  
  function parseData(json) {
	  data=[];
          ...
	  return data;
  }
  
  $('#ddMetrics').show();
  
  
  if(init) {
	nv.addGraph(function() {
	  chart = nv.models.lineWithFocusChart();

	  chart.xAxis
       .axisLabel('Time (s)')
       .tickFormat(d3.format('d'));
    
      chart.yAxis
       .axisLabel(yAxisLabel)
       .tickFormat(d3.format(',.1f'))
       .rotateYLabel(false);

      chart.y2Axis
       .axisLabel(yAxisLabel)
       .tickFormat(d3.format(',.1f'));

      chart.x2Axis
        .axisLabel('Time (s)')
        .tickFormat(d3.format('d'));
    
      d3.select('#chart svg')
        .datum(parseData(jsonData))
	    .call(chart);
    
      nv.utils.windowResize(chart.update);
    
      return chart;
    });
  } else {
	console.log("Updating data");
	d3.select('#chart svg')
	  .datum(parseData(jsonData))
	  .transition().duration(500)
	  .call(chart);
  }
	  
};
```

**Comment by liquidpele** [comment]
Hi there.  A contributor just recently submitted changes that allows nvd3 to use fastdom if it's loaded on the page, which should help a lot with the performance.  You can give it a try by using the latest development branch build, let me know if it helps!

https://github.com/wilsonpage/fastdom

https://github.com/nvd3-community/nvd3/tree/development/build

**Comment by marcinag** [comment]
Hi,

Version of nvd3 with fastdom seems to improve overall performance, but...

My tab still crashes after process memory consumption for Chrome constantly increases with time. Can the update of data cause some memory leak?

Thanks for your help.

**Comment by liquidpele** [comment]
How many data points are we talking about here?

**Comment by marcinag** [comment]
About 5000. I don't think it's the number of data points that is the problem, as if I switch off XHR I have no problems. The problem arises when I have XHR running. Every 10 seconds I make an XHR request to my server and it returns me about 5000 data points, and I want to update my graph with these points (they can be exactly the same as the previous ones if no events happen in the backend).

**Comment by liquidpele** [comment]
Ah, I see, so something isn't getting removed when the points are updated.  This one will take some investigation...

**Comment by portante** [comment]
@marcinag, recently a change when into line charts to obey the presence of "notActive" in the data set.

I plan on using that to draw 5,000+ point lines on a graph, but just select about 50 - 100 points for mouse over, greatly reducing the graph complexity (objects in the DOM, mostly).

You might to try that out to see if that helps here.

**Comment by liquidpele** [comment]
I think this is fixed.   Please open new issues under the novus repo, thanks!
