### ISSUE TITLE
Tooltip position issues

### ISSUE THREAD

**Issue by liquidpele** [nvd3-community/nvd3#3]
Breaks under bootstrap and other CSS-heavy things apparenty, need to look into fixing this either by converting to D3 tooltip or positioning within the container only. 

https://github.com/liquidpele/nvd3/issues/32

**Comment by jamesgarfield** [comment]
I've found that for `multiBarChart` and `multiBarChartHorizontal` the problem appears to be with the initial `pos` value passed to `nv.tooltip.show` from their respective `showTooltip` function variable.

The current implementation looks like the following, and will mis-align tooltips in different ways (see attached)
```
var showTooltip = function(e, offsetElement) {
    var left = e.pos[0] + ( offsetElement.offsetLeft || 0 ),
        top = e.pos[1] + ( offsetElement.offsetTop || 0),
        x = xAxis.tickFormat()(multibar.x()(e.point, e.pointIndex)),
        y = yAxis.tickFormat()(multibar.y()(e.point, e.pointIndex)),
        content = tooltip(e.series.key, x, y, e, chart);

    nv.tooltip.show([left, top], content, e.value < 0 ? 'e' : 'w', null, offsetElement);
};
```
https://github.com/nvd3-community/nvd3/blob/master/src/models/multiBarChart.js#L69
https://github.com/nvd3-community/nvd3/blob/master/src/models/multiBarHorizontalChart.js#L63


I've found that for us, removing the `offsetElement` calculations leads to the tooltip showing up generally where we'd expect them to.

```
var showTooltip = function(e, offsetElement) {
    var left = e.pos[0],
        top = e.pos[1],
        x = xAxis.tickFormat()(multibar.x()(e.point, e.pointIndex)),
        y = yAxis.tickFormat()(multibar.y()(e.point, e.pointIndex)),
        content = tooltip(e.series.key, x, y, e, chart);

    nv.tooltip.show([left, top], content, e.value < 0 ? 'e' : 'w', null, offsetElement);
};
```

I haven't exhaustively tested this kind of fix across all models, but a quick survey across the different models indicates this is a fairly common pattern.

Our use-case is a responsive 4-box 'flowgrid' (position:relative, display:inline-block) style layout (see attached), and this fix has been tested in that scenario. I've also live-edited the example pages at https://nvd3-community.github.io/nvd3/ as a test and the tooltips appear to continue working as expected after the changes.


Stacked Flowgrid
![image](https://cloud.githubusercontent.com/assets/1718770/6114800/9669576c-b06e-11e4-862c-867e14c5abfb.png)

Side-by-side flowgrid
![image](https://cloud.githubusercontent.com/assets/1718770/6114848/f945963e-b06e-11e4-814d-f95ce4f020c0.png)


Stacked Flowgrid after Fix
![image](https://cloud.githubusercontent.com/assets/1718770/6114910/88040b9e-b06f-11e4-97a7-0a22c0e4a527.png)

**Comment by liquidpele** [comment]
fixed.
