### ISSUE TITLE
Charts resize doesn't work

### ISSUE THREAD

**Issue by Martin1887Privado** [nvd3-community/nvd3#30]
Hello.

I have charts in a resizable `div` and in novus 1.15 version on windowResize event charts resized. However, in this version charts don't resize when windowResize event is raised.

This is an example chart:

nv.addGraph(function() {
	    var chart4 = nv.models.pieChart()
		.x(function(d) { return d.key; })
		.y(function(d) { return d.values; })
		.color(d3.scale.category20().range())
		.showLabels(true)
		.pieLabelsOutside(true)
		.labelThreshold(0)
		.labelType('value+percent')
		}); 

	    d3.select("#chart4 svg")
		.datum(data)
		.transition()
		.duration(1200)
		.call(chart4);

	    nv.utils.windowResize(chart4.update);

	    return chart4;
	});

Thanks.

**Comment by liquidpele** [comment]
It's hard to tell, but it looks like your example saves the "chart4" variable inside the nv.addGraph() block, but then the nv.utils.windowResize() is outside that block.   

Regardless, I can't reproduce, I made a new example and it seemed to work just fine.  Are you sure you set the svg and its containers to 100% width and height so it expands with the screen?

**Comment by Martin1887Privado** [comment]
Sorry for the errata, `nv.utils.windowResize()` is inside `nv.addGraph` block because I forgot erase the first `});`.

I have tested in Firefox and Chrome and it doesn't work, containers and svg have width 100%.

This is a complete example (with extra '`' characters, sorry for my poor Markdown knowledge:

HTML:
`<div id="graficas" style="width: 95%; min-width: 50%; height: auto; float: left; border: 1px solid dodgerblue; padding: 10px; display: block; margin-top: 0px; ">

    <div id="chart4" style="background-color: #f4f4f4; width: 100%; height: 430px; margin-top: 10px; padding-bottom: 20px; padding-top: 20px;">

         <svg id="pie" style="height: 420px;"></svg>

    </div>

</div>`

JS:
`
nv.addGraph(function() {
	    var chart4 = nv.models.pieChart()
		.x(function(d) { return d.key; })
		.y(function(d) { return d.values; })
		.color(d3.scale.category20().range())
		.showLabels(true)
		.pieLabelsOutside(true)
		.labelThreshold(0)
		.labelType('percent')
		.tooltipContent(function(key, y, e, graph) {
		    return key + ',' + e.value;
		}); 
`

	`    d3.select("#chart4 svg")
		.datum(data)
		.transition()
		.duration(1200)
		.call(chart4); `

	   nv.utils.windowResize(chart4.update);

	    chart4.pie.dispatch.on("elementClick", function(e) {
		alert(e);
	    });
	    return chart4;
	});

**Comment by liquidpele** [comment]
<svg id="pie" style="height: 420px;"></svg>

You can't limit height or width or it won't expand.

**Comment by Martin1887Privado** [comment]
Height attribute is not restricting, but it increases height. I have just tested the same chart without height attribute and it doesn't resize.

Thanks!

**Comment by liquidpele** [comment]
Well, like I said I can't reproduce.  I made my piechart example expand just fine, so you'll need to provide a jsfiddle or something that I can see what's happening...
