### ISSUE TITLE
Grey color in multiBarHorizontalChart in version 1.7

### ISSUE THREAD

**Issue by Martin1887Privado** [nvd3-community/nvd3#31]
Hello.

I have noticed that bars colors in multiBarHorizontalChart have changed to greyscale instead use d3.scale.category20().range() in version 1.7 and master. In version 1.6 colors are correct.

This is an example chart:

nv.addGraph(function() {
	    var chart = nv.models.multiBarHorizontalChart()
		.x(function(d) { return d.label; })
		.y(function(d) { return d.value; })
		.color(d3.scale.category20().range())
		.margin({top: 30, right: 20, bottom: 50, left: 275})
		.showValues(true)
		.tooltips(true)
		.showControls(true);

	    d3.select"#chart svg")
		.datum(data)
		.transition().duration(500)
		.call(chart);

	    nv.utils.windowResize(chart.update);

	    return chart;
	});

Thanks.

**Comment by liquidpele** [comment]
I think this is fixed in the development branch already, please check :)

**Comment by Martin1887Privado** [comment]
I tested master branch yesterday and it hadn't fixed.

Thanks.

**Comment by liquidpele** [comment]
the development branch is the latest code but might be unstable from time to time.  Master is not updated but I try to keep it stable.  Please check the development branch, not the master branch.

**Comment by Martin1887Privado** [comment]
Ah, ok, sorry, I had misunderstanding!

Thanks.
