### ISSUE TITLE
Styling label text

### ISSUE THREAD

**Issue by jovpet** [nvd3-community/nvd3#33]
It would be nice to have an option to style text as well. I've noticed that in nvd3/build/nv.d3.js on line 8873 default fill is set to black  `.style('fill', '#000')`. It would be nice to let user customize those values and set additional styling for text appearance.

**Comment by liquidpele** [comment]
You can override with CSS using !important I think.

**Comment by jovpet** [comment]
Nope, since this is inline code...

**Comment by liquidpele** [comment]
You can override inline CSS with !important

http://stackoverflow.com/questions/16813220/how-can-i-override-inline-styles-with-external-css

**Comment by lizhongliang** [comment]
I still don't really get this. I want to change the style including font size and color of an axis label. How can I do this?
Thank you.
