### ISSUE TITLE
Reference from and to nvd3.org

### ISSUE THREAD

**Issue by jzipfler** [nvd3-community/nvd3#36]
I do not know how the things are with the creator from nvd3 and @liquidpele, but what is with the webpage (nvd3.org).
What I am interested on is, that the latest source files from this repo gets linked to the page. Or that the page refers to this one.
If you visit the page, there is no sign or comment that the project is maintained here. You get these information only if you visit the github page (look for the sources).

Do not know if that is the right place to talk about that, but maybe it is. ;-)

**Comment by maxArturo** [comment]
I would say that's one of the things you get with OSS - many times the projects get dropped and there are no clear symlinks in the post-mortem documentation. At the very least, there's a cookie trail from the original repo all the way to here. I followed the links and now I know NVD3 is not dead. :smile: 

One would hope to get an updated link in NVD3.org, but that may never happen...

**Comment by liquidpele** [comment]
I have no relation at all to them, I just emailed them to get the status of the project and later again to ask them to link to my fork.  I doubt they'd give up the domain name or anything since they're a business.

**Comment by liquidpele** [comment]
They added me to their repo :p
