### ISSUE TITLE
Enable interactive guideline for multi charts

### ISSUE THREAD

**Issue by initializard** [nvd3-community/nvd3#39]
Request: ability to enable the interactive guideline for lines in multi-charts. 

I fiddled around and got it mostly working, but I am barely familiar with the nvd3 source code.

**Comment by liquidpele** [comment]
Feel free to send me a pull request to the development branch!

**Comment by sanjutoyou** [comment]
are we also working on the refactoring the nvd3 to make it modular. Like to add focus / view finder in any chart as option .

**Comment by liquidpele** [comment]
Kind of... I think more charts need the focus option and it could be handled better to make it more modular for sure.  I combined a few of the models toward this goal already...
