### ISSUE TITLE
size and forceSize option renames to pointSize and forcePoint break angularjs-nvd3-directives

### ISSUE THREAD

**Issue by portante** [nvd3-community/nvd3#43]
As of https://github.com/nvd3-community/nvd3/commit/c903ef6109b752eebfcc32de8e0053279f3c0ad1, angularjs-nvd3-directives.js breaks, because they reference some or all of the old option names.

Could we mark the names as obsolete for one revision, leaving an alias, and then remove them later?

**Comment by liquidpele** [comment]
Yea, should probably make the old options still available as well for a bit before removing them if another app is depending on them...

**Comment by portante** [comment]
I'll post something as I am currently working with this now.

**Comment by liquidpele** [comment]
Cool.  I had to rename them though, they were terribly named and it took me way too long to figure out what they all did.

**Comment by liquidpele** [comment]
Oops, didn't mean to close yet.

**Comment by portante** [comment]
I agree with the rename, glad you did it.  Will post "soon".

**Comment by portante** [comment]
@liquidpele, still planning on fixing this, hopefully today.

**Comment by liquidpele** [comment]
Oh really?  I thought you guys had moved that whole repo and so were just going to fix it there.   We can fix here too though, no worries.

**Comment by liquidpele** [comment]
Actually, let me just add you to the org...

**Comment by portante** [comment]
@liquidpele, ah, sorry, yes this is community, will fix in the novus one.

**Comment by liquidpele** [comment]
Actually I was talking about the angular-nvd3-directives repo ;)

**Comment by portante** [comment]
@liquidpele, yes, you are right that it is probably best to just fix it there.
