### ISSUE TITLE
Publish nvd3 community version in the NPM registry

### ISSUE THREAD

**Issue by jjzazuet** [nvd3-community/nvd3#45]
Hi. Like the title says. I looked in the registry but I could only find version 1.1.15-beta.

https://www.npmjs.com/package/nvd3

You guys are currently at 1.7 right?

Thanks!

**Comment by liquidpele** [comment]
I registered with bower, but not sure how to register with npm...

**Comment by jjzazuet** [comment]
This could help:

https://gist.github.com/coolaj86/1318304

Also, note that `package.json` should also point to a main javascript file which would be considered the "index" export of the package. Two examples from Facebook flux and the folks at C3:

https://github.com/facebook/flux/blob/master/package.json
https://github.com/masayuki0812/c3/blob/master/package.json

Note that C#3 declares `d3` as a module dependency, in addition to their development dependencies.

Hope this is useful. Thanks!

**Comment by jjzazuet** [comment]
One more thing. Note that in order for others to `require()` nvd3, one of the main javascript file should declare an `module.exports` object so that it can be used as a node module.

https://docs.npmjs.com/misc/faq

Thanks!

**Comment by jjzazuet** [comment]
Looking at the source, seems to me that `core.js` would be a nice place to declare node exports.
