### ISSUE TITLE
Negative y axis values show as positive

### ISSUE THREAD

**Issue by franklovecchio** [nvd3-community/nvd3#46]
![screen shot 2015-01-30 at 11 35 55 am](https://cloud.githubusercontent.com/assets/341277/5981076/3ea5e6d2-a874-11e4-83bd-c8c54bbf3462.png)

**Comment by dougmillerknd** [comment]
Are you expecting a negative sign on the 104.99878?

It is there, just cut off by the edge of the graph (you can see a line of pixels there for it). 
When I ran into this issue I either added padding to the chart or formatted to fewer decimal places.
