### ISSUE TITLE
linePlusBarChart x axis 

### ISSUE THREAD

**Issue by dbackowski** [nvd3-community/nvd3#47]
In linePlusBarChart on x axis first and last values are cut off (tested on 1.7.0.).

![zrzut ekranu 2015-02-02 o 09 26 01](https://cloud.githubusercontent.com/assets/567457/5997762/dede1988-aabf-11e4-9706-dbcb09ab55b1.png)

On old nvd3 (before fork). 

![zrzut ekranu 2015-02-02 o 09 26 31](https://cloud.githubusercontent.com/assets/567457/5997795/2db80ba4-aac0-11e4-8965-540f74b6fa70.png)

**Comment by liquidpele** [comment]
Huh, that's weird!

**Comment by dbackowski** [comment]
Is there any chances to fix this ?
Novus closed #290 because "this is by design"

**Comment by liquidpele** [comment]
I reopened the novus issue, closing this one.
