### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by amenadiel** [nvd3-community/nvd3#52]
Hi guys

I was trying to check if version 1.7.0 is compatible with d3js 3.5.3, but I noticed that, even with the current dependency (d3 3.3.13) some tests do fail.

```sh
Chrome 41.0.2272 (Linux): Executed 126 of 132 (30 FAILED) (skipped 6) (1.988 secs / 0.355 secs)
```

Can you please confirm that your task `grunt karma` runs ok on your side?

**Comment by liquidpele** [comment]
I've never run the tests to be honest... I'm not even sure what their state was when I forked.  

I test with d3 3.5 myself, 3.3 is just the min requirement.

**Comment by amenadiel** [comment]
So far I've noticed no incompatibilities with version 3.5. At this point I added a resolve entry to my bower.json so I could specify version 3.5.0

**Comment by robinfhu** [comment]
Pretty sure tests were working in novus/nvd3 master.

**Comment by portante** [comment]
PR #58 has them working again.  Check it out.

**Comment by amenadiel** [comment]
Amazing!
