### ISSUE TITLE
Click on a line charts legend breaks tooltips in IE11

### ISSUE THREAD

**Issue by mpGitHub** [nvd3-community/nvd3#66]
Line chart issue:

Clicking on a Legend to filter just on that item breaks the tooltip.  This same bug occurs if you update the chart via: d3.select("#myChart").datum(chartData).call(chart);

The problem seems to occur because duplicate IDs for "nv-point-clips" are created every time the chart is updated.  Duplicate <g> ids for "nv-point-clips" are created in chrome as well, but chrome seems to handle this situation better.  Still, updating the chart many times could potentially cause 100's of these duplicates to occur bloating it and eventually slowing the chart down.

If I manually delete all DOM elements for "nv-point-clips" except for the last one the tool tips start working properly in IE11.

Can something be added to clean up the old "nv-point-clips" before new ones are added?  The duplicates/old ones are created/left here:

   - <g class="nv-linesWrap nvd3-svg"  
      - <g class="nv-scattterWrap nvd3-svg" 
           <g id="nv-point-clips"   **(old one)**
            <g id="nv-point-clips"  **(old one)**
            <g id="nv-point-clips"  **(old one)**
            <g id="nv-point-clips"  **(current chart - keep this one)**

**Comment by liquidpele** [comment]
Yea, seems like the bigger issue is that the old stuff isn't being removed then...

**Comment by liquidpele** [comment]
Can you open this issue under the novus repo?   They added me as a contributor there and it'll get a lot more eyes.  

https://github.com/novus/nvd3
