### ISSUE TITLE
Labeling X-axis with text on a multiBarChart

### ISSUE THREAD

**Issue by njuki** [nvd3-community/nvd3#69]
Hi guyz,

I  am trying to label x-axis with text without success. It currently displays "NaN%". How do I fix this? 
Also, When the barchart first loads, the bars are grouped by default. Is there away I can force them to get stacked.  Below is a screen capture
Thank you in advance for your assistance.
![screen shot 2015-02-25 at 7 26 20 pm](https://cloud.githubusercontent.com/assets/483848/6375343/8a019faa-bd27-11e4-9dfc-a720632b3f1c.png)

**Comment by liquidpele** [comment]
Please open issues under the novus repository now, thanks!
