### ISSUE TITLE
donut pie chart will shrink if in Bootstrap 3 tabs

### ISSUE THREAD

**Issue by maplesap** [nvd3-community/nvd3#70]
Hi, I'm having a problem with v1.7.1. If I have a donut pie chart inside a bootstrap tab, the pie sections will shrink if moused over.

This does not happen in v1.1.15-beta.

Here is a plnkr:
http://plnkr.co/edit/G1Q8QiFpLnsA9116o2wq?p=preview

(click second tab and mouse over)

The issue is described in more detail here:
https://github.com/krispo/angular-nvd3/issues/92

**Comment by portante** [comment]
@maplesap, you might want to file this against novus/nvd3.

**Comment by liquidpele** [comment]
Yup, please open the issue under novus (we have commit access there now!) and we'll look at it :)

**Comment by liquidpele** [comment]
Just FYI, you can turn off growOnHover to work around this since that's what is causing the issue, I updated your plunker to show this:

http://plnkr.co/edit/Z5sNFQ1AEHWYnMR1au1F?p=preview
