### ISSUE TITLE
tooltip error in shadow-dom

### ISSUE THREAD

**Issue by HedCET** [nvd3-community/nvd3#72]
nvd3 tooltip don't hide inside polymer element
& i solved it by adding
```    nv.tooltip.cleanup = function() {
$("* /deep/ .nvtooltip").remove();```

pls support tooltip in shadow-dom

**Comment by liquidpele** [comment]
Tooltips were recently refactored, so this is probably not necessary anymore.  Here is the relevant pull request for the refactor:  https://github.com/novus/nvd3/pull/851

**Comment by liquidpele** [comment]
PS: the novus repo is the most updated one now, they added me as a contributor to their org so I have complete access there, so nvd3-community is more of just a backup now, and the novus repo is back to being the main one.
