### ISSUE TITLE
display spinner on click of legends

### ISSUE THREAD

**Issue by rbsl-jogendra** [nvd3-community/nvd3#73]
how can we display a spinner or loading image when legend selected/unselected ?

**Comment by liquidpele** [comment]
Are you doing something special when they click the legend?  disabling/enabling stuff shouldn't be so slow as to require that...

**Comment by rbsl-jogendra** [comment]
actually we are displaying our data in multibar chart, so if the data is too large and we have almost 10+ legends.In that case when we select/unselect any legend then it take some time to redraw the chart,So we are thinking of to add a loading/spinner for that time. Is it possible ?

**Comment by liquidpele** [comment]
There is a legendClick event on the legend you could use... so for instance:

    chart.legend.dispatch.on('legendClick', function(d, i) {  
        // manually put the spinner somewhere 
    });

As for telling when it finishes rendering, there is a renderEnd dispatch on the chart's dispatch object set by nv.utils.renderWatch() I think... I haven't used that before though...  

Oh, I just noticed we are in nvd3-community... please open all new issues under the novues/nvd3 repo.  They added me as a full contributor there so we've just been doing all dev based off that main repo again.  Closing this one.
