### ISSUE TITLE
1.7.1 Tag

### ISSUE THREAD

**Issue by antoine-richard** [nvd3-community/nvd3#74]
Hello,
Can you push a tag for 1.7.1?

Thanks.
Antoine

**Comment by krasnoukhov** [comment]
That would be pretty nice in order to use bower again!

**Comment by liquidpele** [comment]
Can you not use the 1.7.1 tag on the novus repo?

**Comment by krasnoukhov** [comment]
Wow, I didn't noticed that. Makes sense, thanks

**Comment by liquidpele** [comment]
I went ahead and pushed up all the tags too, but yea, we're doing the active dev there now since they added me as a full contributor to their repo.

**Comment by krasnoukhov** [comment]
Sounds good! So I assume that this repo will be deprecated in a future?

**Comment by liquidpele** [comment]
Dunno, I'm just keeping them in sync for the most part for now... in case novus decides to drop off the face of the earth again or something ;)

**Comment by krasnoukhov** [comment]
Hahaha, I see! Anyway, keep up the good work, thank you so much :sparkles: :tophat:

**Comment by antoine-richard** [comment]
Didn't notice the activity switched to the novus repo. I'll pull nv from there. Thanks
