### ISSUE TITLE
StackAreaChart with the same starting point

### ISSUE THREAD

**Issue by jshek** [nvd3-community/nvd3#75]
Hello,

     Is it possible to use the StackAreaChart to show 2 data set with the same starting point?

For example in the attachment I have the fund and it's benchmark. They both start at 10,000 and the graph show what happen over a period of times.

![capture](https://cloud.githubusercontent.com/assets/11724288/6903140/471b1bd4-d6e6-11e4-9e70-4e83e9b29c5e.JPG)

   I would to use D3 for the above chart. Please advise.

Thanks,
-John

**Comment by liquidpele** [comment]
stacked area is going to be... well... stacked... so for them to have the same exact point, one value would have to be zero.   Or am I not understanding your question?

**Comment by liquidpele** [comment]
Oh, also this repo is in maintenance mode, please open issues in the novus repo now, thanks and sorry for any confusion there... they added me as a contributor to their repo so we're just doing the dev there now :)
