### ISSUE TITLE
Scatter chart - always centered the point

### ISSUE THREAD

**Issue by jshek** [nvd3-community/nvd3#76]
Hi,

   Is it possible to plot the points in the middle regardless of the data? Basically, i need to recalculate the x and y axis range so, that the points are always in the middle.

![capture2](https://cloud.githubusercontent.com/assets/11724288/6903265/18e91de6-d6e7-11e4-9adf-28ef70270746.JPG)

  I would like 2 points to be in the middle of the chart so, it would be easier to see.

Thanks,
-John

**Comment by liquidpele** [comment]
Hey there, yes you can manually set the scales of the yAxis and xAxis objects on the chart if you want.  See the documentation for all the options on the "axis" object.

Also, please open further issues/question in the novus repo now, they added me as a contributor so we're just doing all the dev work there and this repo is maintenance mode :)

**Comment by liquidpele** [comment]
https://nvd3-community.github.io/nvd3/examples/documentation.html#axis
