### ISSUE TITLE
Can I make this type of graph out of the box?

### ISSUE THREAD

**Issue by dagumak** [nvd3-community/nvd3#77]
http://personalfinancesoftwarereviews.com/wp-content/gallery/mint-update-trends/mint-trends8.png

I've looked through the examples, and I don't see one that is exactly like this and wasn't sure how much would I have to customise to get the same graph.

**Comment by liquidpele** [comment]
Not one exactly like that now.  Closest thing is the linePlusBarChart.  

http://nvd3-community.github.io/nvd3/examples/linePlusBarChart.html

Or without the line there is the multiBarChart:

http://nvd3-community.github.io/nvd3/examples/multiBarChart.html   (click 'stacked' in the upper left)

**Comment by dagumak** [comment]
@liquidpele Thanks for the quick reply. I appreciate it!
