### ISSUE TITLE
how to display data in the tooltip using NVD3.JS

### ISSUE THREAD

**Issue by OYRS** [nvd3-community/nvd3#81]
I have the folowing data:

Date / Value1(0 or 1) /Value2 (string).

I h'de like to know how to display this data in a single line graph in which the value2 appear in the tooltip of the graph.

I try something but I get severals lines as the following picture:
![im4](https://cloud.githubusercontent.com/assets/8937672/9058376/c3fd084c-3aa0-11e5-93d8-4749e11c85a8.png)

**Comment by bwarren2** [comment]
You want to write a [custom](https://github.com/novus/nvd3/blob/f54d2d6ff35190ec4664ee7d52d763ac4759dbf5/examples/documentation.html#L352) [contentgenerator](https://github.com/novus/nvd3/blob/27d9771cba0016ec601ade9205fa55669735fb5e/src/tooltip.js#L76-L135).

**Comment by liquidpele** [comment]
Please open all issues in the novus repo as all active development is back there now, thanks!
