### ISSUE TITLE
Accessing Directive Api

### ISSUE THREAD

**Issue by jstromwick** [nvd3-community/nvd3#85]
I would like to be able to access the directive's internal `scope.api` from my controller. The quick start makes it seem like exposing the api is intended (http://krispo.github.io/angular-nvd3/#/quickstart), but I can't seem to get it working.

I'm using the directive like so:

	<nvd3 options="chartOptions" data="chartData" api="chartApi"></nvd3>

My expectation would be that after the directive is initialized the `chartApi` property on my controller would expose the directive's internal `scope.api` object. It looks like this is not the case however, as the directive resets the value of `scope.api` in the link function.

Is this intentional? Is there a way to get access to the `scope.api`? 

Cheers!

**Comment by liquidpele** [comment]
Wrong project.  This has zip to do with angular.

**Comment by jstromwick** [comment]
My bad, sorry about the mix up!

**Comment by liquidpele** [comment]
Np!
