### ISSUE TITLE
x-domain disregarded

### ISSUE THREAD

**Issue by rwijtvliet** [nvd3-community/nvd3#86]
I think I've found a bug, but it might just be that I overlooked a setting. 

When creating a multichart with multiple series with unequal x-domains, each series appears to be stretched across the x-axis so that it fills up the entire space - at least, if the series have unequal type.

E.g. Using this block:

    var ch = nv.addGraph(function() {
                    var chart = nv.models.multiChart()
                            .margin({top: 30, right: 60, bottom: 50, left: 70})
                    d3.select('#chart svg')
                            .datum(series)
                            .call(chart);
                    return chart;
    }); 

gives a correct result with `series1` (with the second line extending further right than the first), but not with `series2`.

    var series1 = [
                    {   type: 'line',
                        key: 'line1',
                        values: [{x:1, y:0}, {x:2, y:2}],
                        yAxis: 1},
                    {   type: 'line',
                        key: 'line2',
                        values: [{x:1, y:0}, {x:2, y:1}, {x:3, y:0}],
                        yAxis: 1}
                ];
    var series2 = [
                    {   type: 'line',
                        key: 'line1',
                        values: [{x:1, y:0}, {x:2, y:2}],
                        yAxis: 1},
                    {   type: 'area',
                        key: 'area2',
                        values: [{x:1, y:0}, {x:2, y:1}, {x:3, y:0}],
                        yAxis: 1}
                ];

![selection_002](https://cloud.githubusercontent.com/assets/4106013/10541692/4a0be20e-7413-11e5-86ae-d815580751da.jpg)
![selection_003](https://cloud.githubusercontent.com/assets/4106013/10541691/4a0bf064-7413-11e5-8e5e-5cab0ea6ab5b.jpg)

**Comment by liquidpele** [comment]
Hi there... please open all defects with the novus repo, this one is in maintenance mode and all active development is done over there, thanks! 

When you do, please provide a jsfiddle showing the issue, using the latest stuff in the master branch (you can link to it using rawgit.com).   Thanks!
