### ISSUE TITLE
Only formatted x values are given to InteractiveGuideline and there is no way to update the visual display within other events.

### ISSUE THREAD

**Issue by schryer** [nvd3-community/nvd3#87]
My goal is to overcome the problem that only formatted x values are given to the Interactive guideline. Currently, (1.8.1) it only shows the last and first values in the series as I change the hover.

However, I am able to track the x-values when I use the following event:

chart.interactiveLayer.dispatch.on('elementMousemove.name', function(b) {
                console.log("Mouse move...", b);
});

Yet, with this I am unable to update the interactive display....   Perhaps there is a workaround that I am unaware of.

**Comment by liquidpele** [comment]
Pretty sure this is already fixed in the master branch in the novus repo.    For future reference, the novus repo is currently used for active development so please open issues there.   Thanks!

**Comment by liquidpele** [comment]
Yea, looks like lineChart and stackedArea were both fixed:

https://github.com/nvd3-community/nvd3/issues/87

https://github.com/novus/nvd3/pull/1276

**Comment by schryer** [comment]
Sorry for the trouble, and thank you for the links.
