### ISSUE TITLE
How do I avoid overlapping pieChart's series.

### ISSUE THREAD

**Issue by Kyeongan** [nvd3-community/nvd3#92]
I feel there is a way to avoid overlapping series. But I couldn't find it. Anyone give some idea how do I avoid it. Also, I would like to have a legend as a single line because just I have a space. Is there any variables to handle? Thanks

![screen shot 2015-11-25 at 4 32 52 pm](https://cloud.githubusercontent.com/assets/5505099/11411101/74e19cdc-9392-11e5-90a9-9d7287c8dade.png)

**Comment by liquidpele** [comment]
Please open all issues/PRs under novus project, thx.
