### ISSUE TITLE
chart.title not dynamic

### ISSUE THREAD

**Issue by lunarin** [nvd3-community/nvd3#93]
Hi there,

I've been implementing nvd3 in my Meteor application and have gotten the charts to redraw upon change - by using :

Template.charts.onRendered(function() {
  Tracker.autorun(function() {
   ...
  });
});

However, the title of the charts is not changing. Is this a known issue?

**Comment by liquidpele** [comment]
this project is only for maintenance, please open any new things under the novus project.
