### ISSUE TITLE
How to add values on top of historicalBarChart bars like showValues property on discreteBarChart?

### ISSUE THREAD

**Issue by edouard-lopez** [nvd3-community/nvd3#94]
Working on a teammate with angular-nvd3 we are willing to add values on top of the 
[`historicalBarChart`](https://nvd3-community.github.io/nvd3/examples/documentation.html#historicalBarChart) similar to what exists on [`discreteBarChart`](https://nvd3-community.github.io/nvd3/examples/documentation.html#discreteBarChart) throug `showValues` property. But to our surprise there is no such property for `historicalBarChart`

How can we add value on top of each bar?

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
