### ISSUE TITLE
Ticks number for nvd3 cumulativechart not working

### ISSUE THREAD

**Issue by violentr** [nvd3-community/nvd3#95]
I am using Nvd3 library cumulativeChart with coffee-script and I have an issue with ticks (xAxis) on my graph, the dates are overlapping each other when the date range is too big. Any ideas how to solve this issue?
I have described an issue in detail here 
http://stackoverflow.com/questions/34742279/ticks-number-for-nvd3-cumulativechart-not-working

Thank you in advance

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
