### ISSUE TITLE
Interactive tools don't update on lineChart under v1.8

### ISSUE THREAD

**Issue by azazdeaz** [nvd3-community/nvd3#98]
Hi,

The tooltip and interactiveGuideline aren't updating with v1.8.1.

Here is a minimal jsbin about the issue: http://jsbin.com/dixeji/edit?html,output
If you change the nvd3 versions in the html tab to 1.7.1 everything works fine.

Thanks a lot for your work on this library!

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
